language: node_js
node_js:
  - "14"

dist: trusty
sudo: false
addons:
  chrome: stable

cache:
  directories:
    - node_modules
    - dist

install:
  - npm install

jobs:
  allow_failures:
    - name: test app
    - name: check styles by linter

  include:
    - stage: build
      script:
      - ng lint
      name: check app by linter
    -
      script:
      - npm run stylelint
      name: check styles by linter
    -
      script:
      - ng test --watch=false --browsers ChromeHeadless
      name: test app
    -
      script:
      - ng build --prod --base-href /GreenCityClient/ --deploy-url /GreenCityClient/ --aot=false --build-optimizer=false
      name: build app
    -
      script:      
      -  ng build --prod --base-href /GreenCityClient/ --outputPath=dist_aot && rm -rf dist_aot
      name: build app using aot compilation
    - stage: deploy
      script: skip
      name: deploy on gh_pages
      if: branch IN (dev, master)
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $TRAVIS_GH_TOKEN
        local_dir: dist/GreenCityClient
        on:
          branch: dev
   
