name: CI/CD GreenCityClient

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ master, dev, sonar_fix ]
  pull_request:
    branches: [ master, dev, sonar_fix ]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Install
        run: |
          npm install
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get install ./google-chrome-stable_current_amd64.deb -y
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.2.0.1873-linux.zip
          unzip sonar-scanner-cli-4.2.0.1873-linux.zip
          sudo mv sonar-scanner-4.2.0.1873-linux /opt/sonar-scanner
      
      - name: JS Linter
        run: npm run lint

      - name: CSS Linter
        run: npm run stylelint

      - name: Unit Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        #continue-on-error: true
        run: |
          ng test --watch=false --progress=false --codeCoverage=true --browsers=ChromeHeadless
#          /opt/sonar-scanner/bin/sonar-scanner
#           -Dsonar.organization=ita-social-projects
#           -Dsonar.projectKey=ita-social-projects-green-city-client
#           -Dsonar.host.url=https://sonarcloud.io
#           -Dsonar.sources=src
#           -Dsonar.exclusions=**/node_modules/**
#           -Dsonar.tests=src
#           -Dsonar.test.inclusions=**/*.spec.ts
#           -Dsonar.javascript.lcov.reportPaths=coverage/GreenCityClient/lcov.info
#           -Dsonar.qualitygate.wait=true
        
      - name: E2E Tests
        run: npx ng e2e --protractor-config=e2e/protractor-ci.conf.js

      - name: Build
        run: |
          npx ng build --prod --delete-output-path --base-href=/GreenCityClient/ --outputPath=dist_aot && rm -rf dist_aot
          npx ng build --prod --base-href=/GreenCityClient/ --aot=false --build-optimizer=false
      
      - name: Deploy ðŸš€
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist/GreenCityClient
          CLEAN: true 
